bills/urls.py
from django.urls import path
from .views import BillListView, BillDetailView

# Create your views here.
urlpatterns = [
    path('', BillListView.as_view(), name='bill_list'),
    path('<int:pk>/', BillDetailView.as_view(), name='bill_detail'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic.base import TemplateView 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")), 
    path("accounts/", include("django.contrib.auth.urls")), 
    path("", include("maintenance.urls")),
    path("rentals/", include("rentals.urls")),
    path("bills/", include("bills.urls")),
    path("contacts/", include("contacts.urls")),
    path("maintenance/", include("maintenance.urls")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maintenance/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse, reverse_lazy
from rentals.models import RentalProperty

class Maintenance(models.Model):

    URGENCY_CHOICES = [
        ('Low', 'Low'),
        ('High', 'High'),
    ]

    urgency = models.CharField(max_length=10, choices=URGENCY_CHOICES, default='Medium')
    property = models.ForeignKey(RentalProperty, on_delete=models.CASCADE)
    date_reported = models.DateTimeField(auto_now_add=True)
    pending = models.BooleanField(default=True)
    description = models.TextField(default='')


    def __str__(self):
        return f"{self.urgency} - {self.property} ({self.date_reported.strftime('%Y-%m-%d')})"
    
    def get_absolute_url(self):
        return reverse("maintenance_detail", kwargs={"pk": self.pk})
    
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>{% block title %}URA Operations{% endblock title %}</title>
      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
   </head>
   <body>
      <header>
         {% if user.is_authenticated %}

   
         <div class = "header">
            <h1>Urban Renewal Associates</h1>
          <p></p>
            <div class="logout-container">
               <h3>Welcome <span style = "color: #c59f8c; font-weight: 700">{{ user.username }}</span></h3>
            
               <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit">Log Out</button>
               </form>
               </div></div>
         
         {% endif %} 
      </header>
      <main>
         
        {% block content %} 
        {% endblock content %}
     </main>
     <!-- Bootstrap JavaScript Bundle -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
   </body>
</html>

templates/bill_detail.html
{% extends "base.html" %} 
{% block title %}URA Bills{% endblock title %} 
{% block content %} 
      <div class="container">
        <table>
          <thead>
             <tr>
         <th> {{ object.name }}</th>
              </tr>
          </thead>
          <tbody><tr><td>
                  <p style = "margin: 0"><strong>Phone:</strong> {{ object.phone }}</p>
                  <p style = "margin: 0"><strong>Website:</strong> {{ object.website }}</p>
                  <p style = "margin: 0"><strong>Account Number:</strong> {{ object.account_number }}</p>
                  <p style = "margin: 0"><strong>Autopay:</strong> {{ object.autopay }}</p>
                  <p style = "margin: 0"><strong>Username:</strong> {{ object.username }}</p>
                 </td> </tr></tbody>

        </table>
                 <p></p> <button onclick="window.history.back()" style="background:none;border:none;cursor:pointer;">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                        </svg>
                        Back
                      </button>
            </div>
      {% endblock content %}

templates/bill_list.html
{% extends "base.html" %} 
{% block title %}URA Bills{% endblock title %} 
{% block content %} 
      <div class="container">
         <h1>Bill List</h1>
         <table>
            <thead>
               <tr>
                  <th>Name</th>
               </tr>
            </thead>
            <tbody>
               {% for bill in object_list %}
               <tr>
                  <td><a href="{% url 'bill_detail' bill.pk %}">{{ bill.name }}</a></td>
               </tr>
               {% endfor %}
            </tbody>
         </table>
         <p></p>
         <button onclick="window.history.back()" style="background:none;border:none;cursor:pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
            Back
          </button>
      </div>
      {% endblock content %}   

templates/contact_detail.html
{% extends "base.html" %} 
{% block title %}URA Contacts{% endblock title %} 
{% block content %} 
      <div class="container">
        <table>
          <thead>
             <tr>
         <th> {{ object.business }}</th>
              </tr>
          </thead>
          <tbody><tr><td>
                  <p style = "margin: 0"><strong>Business Phone:</strong> {{ object.bus_phone }}</p>
                  <p style = "margin: 0"><strong>Contact:</strong> {{ object.contact }}</p>
                  <p style = "margin: 0"><strong>Contact Phone:</strong> {{ object.cont_phone }}</p>
                </td> </tr></tbody>

              </table>
                  <p></p>
      <button onclick="window.history.back()" style="background:none;border:none;cursor:pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
            Back
          </button>
            </div>
      {% endblock content %}

templates/contact_list.html
{% extends "base.html" %} 
{% block title %}URA Contacts{% endblock title %} 
{% block content %} 
      <div class="container">
         <h1>Contact List</h1>
         <table>
            <thead>
               <tr>
                  <th>Business</th>
               </tr>
            </thead>
            <tbody>
               {% for contact in object_list%}
               <tr>
                  <td><a href="{% url 'contact_detail' contact.pk %}" >{{ contact.business }}</a></td>
               </tr>
               {% endfor %}
            </tbody>
         </table>
         <p></p>
         <button onclick="window.history.back()" style="background:none;border:none;cursor:pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
            Back
          </button>
      </div>
{% endblock content %}

templates/home.html
   {% extends "base.html" %} 
   {% block title %}URA Operations{% endblock title %} 
   {% block content %} 
   {% if user.is_authenticated %}
   <div class="container">
      <div class = card-wrapper>
            <a href="{% url 'penwell_list' %}" class="card-link">
               <div class="card small-card">
                  <h3 class="card-title">Penwell Building</h3>
               </div></a>
            <a href="{% url 'residential_list' %}" class="card-link">
               <div class="card small-card">
                  <h3 class="card-title">Residential Properties</h3>
               </div>
            </a>
            <a href="{% url 'bill_list' %}" class="card-link">
               <div class="card small-card">
                  <h3 class="card-title">Bills</h3>
               </div>
            </a>
            <a href="{% url 'contact_list' %}" class="card-link">
               <div class="card small-card">
                  <h3 class="card-title">Contacts</h3>
               </div>
            </a>
            <a href="{% url 'maintenance_list' %}" class="card-link">
               <div class="card small-card">
                  <h3 class="card-title">Maintenance</h3>
               </div>
            </a>
            </div>
   </div>
<!-- Pending Maintenance Requests -->
<div class="container">
   <h1>Pending Maintenance Requests</h1>
   <table>
      <thead>
         <tr>
            <th style = "width: 40%">Property</th>
            <th style = "width: 60%">Description</th>
         </tr>
      </thead>
      <tbody>
         {% for maintenance in object_list %}
           {% if maintenance.pending == True %}
              {% if maintenance.urgency == 'High' %} 
              <tr style="background-color: #fef2f2;">
               {% else %}
               <tr>
               {% endif %}            
               <td style = "width: 40%"><a href="{% url 'maintenance_detail' maintenance.pk %}">{{ maintenance.property }}</a></td>
               <td style = "width: 60%">{{ maintenance.description }}</td>
            </tr>
            {% endif %}
         {% endfor %}
      </tbody>
   </table>
</div>
  
   {% else %}
               <div class="login-container">
                  <h2>URA Operations</h2>
               <p style = "text-align: center;">You are not logged in</p>
               <div style = "text-align: center;">
               <a href="{% url 'login' %}">Log In</a>
            |
               <a href="{% url 'signup' %}">Sign Up</a></div></div>
   {% endif %}
   {% endblock content %}

templates/maintenance_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}URA Maintenance{% endblock title %} 
{% block content %}
<div class="container">
<h3>Delete maintenance request for {{ object.property }}</h3>
<form action="" method="post">{% csrf_token %}
{{ form|crispy }}
<button class="del-button" type="submit">Delete</button>
</form>
<a href="{% url 'maintenance_list' %}" >
  <button  style="background:none;border:none;cursor:pointer;">
     <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
       <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
     </svg>
     Back
   </button></a>

</div>
{% endblock content %}

templates/maintenance_detail.html
{% extends "base.html" %} 
{% block title %}URA Maintenance{% endblock title %} 
{% block content %} 

<div class="container">
  <table>
    <thead>
       <tr>
   <th> {{ object.property }}</th>
        </tr>
    </thead>
    <tbody><tr><td>
            <p style = "margin: 0"><strong>Urgency:</strong> {{ object.urgency }}</p>
            <p style = "margin: 0"><strong>Date Reported:</strong> {{ object.date_reported }}</p>
            <p style = "margin: 0"><strong>Pending:</strong> {{ object.pending }}</p>
            <p style = "margin: 0"><strong>Description:</strong> {{ object.description }}</p>
          <p></p>
      <p style="margin: 0"><a href="{% url 'maintenance_edit' object.pk %}">Edit</a>&nbsp&nbsp&nbsp
         <a href="{% url 'maintenance_delete' object.pk %}">Delete</a>
         </p>
        </td> </tr></tbody>

      </table>
         <p></p>
         <a href="{% url 'maintenance_list' %}" >
          <button  style="background:none;border:none;cursor:pointer;">
             <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
               <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
             </svg>
             Back
           </button></a>
      </div>
{% endblock content %} 

templates/maintenance_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}URA Maintenance{% endblock title %} 
{% block content %}
<div class="container">
<h3>Edit Maintenance Request for {{ object.property }}</h3>
<form action="" method="post" style="text-align: left;">{% csrf_token %}
    {{ form | crispy }}
    <button class= "edit-button" type="submit">Update</button>
    </form>
    <a href="{% url 'maintenance_list' %}" >
      <button  style="background:none;border:none;cursor:pointer;">
         <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
           <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
         </svg>
         Back
       </button></a>
</div>
{% endblock content %}

templates/maintenance_list.html
{% extends "base.html" %} 
{% block title %}Penwell Properties{% endblock title %} 
{% block content %} 
      <!-- Pending Maintenance Requests -->
      <div class="container">
         
         <a href="{% url 'maintenance_new' %}"><button class = "maintenance-button">Submit Maintenance Request</button></a>
        <p></p> <h1>Pending Maintenance Requests</h1>
         <table>
            <thead>
               <tr>
                  <th style = "width: 40%">Property</th>
                  <th style = "width: 60%">Description</th>
               </tr>
            </thead>
            <tbody>
               {% for maintenance in object_list %}
                 {% if maintenance.pending == True %}
                   {% if maintenance.urgency == 'High' %} 
                     <tr style="background-color: #fef2f2;">
                   {% else %}
                      <tr>
                   {% endif %} 
                     <td style = "width: 40%"><a href="{% url 'maintenance_detail' maintenance.pk %}">{{ maintenance.property }}</a></td>
                     <td style = "width: 60%">{{ maintenance.description }}</td>
                  
                  </tr>
                  {% endif %}
               {% endfor %}
            </tbody>
         </table>
      </div>

      <!-- Maintenance History -->
      <div class="container">
         <h1>Maintenance History</h1>
         <table>
            <thead>
               <tr>
                  <th style = "width: 40%">Property</th>
                  <th style = "width: 60%">Description</th>
               </tr>
            </thead>
            <tbody>
               {% for maintenance in object_list %}
                   {% if maintenance.pending == False %}
                     {% if maintenance.urgency == 'High' %} 
                       <tr style="background-color: #fef2f2;">
                      {% else %}
                        <tr>
                      {% endif %} 
                        <td style = "width: 40%"><a href="{% url 'maintenance_detail' maintenance.pk %}">{{ maintenance.property }}</a></td>
                        <td style = "width: 60%">{{ maintenance.description }}</td>
                        
                     </tr>
                  {% endif %}
            
               {% endfor %}
            </tbody>
         </table>
         <p>     
         </p><a href="{% url 'home' %}" >
         <button  style="background:none;border:none;cursor:pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
            Back
          </button></a>
      </div>
      {% endblock content %}

templates/maintenance_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}URA Maintenance{% endblock title %} 
{% block content %}
<div class="container">
<h2>New Maintenance Request</h2>
<form action="" method="post" style="text-align: left;">{% csrf_token %}
    {{ form | crispy }}
    <button class= "edit-button" type="submit">Save</button>
    </form>
    <a href="{% url 'maintenance_list' %}" >
      <button  style="background:none;border:none;cursor:pointer;">
         <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
           <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
         </svg>
         Back
       </button></a>
</div>
{% endblock content %}

templates/penwelldetail.html
{% extends "base.html" %} 
{% block title %}Penwell Properties{% endblock title %} 
{% block content %} 
      <div class="container">
        <table>
          <thead>
             <tr>
         <th> {% if object.apt_numb > 0 %}{{ object.apt_numb }}
          {% else %}{{ object.name }}{% endif %}
         </th>
              </tr>
          </thead>
          <tbody><tr><td>
         <p style = "margin: 0"><strong>Is Available:</strong> {{ object.is_available }}</p>
         <p style = "margin: 0"><strong>Tenant Name:</strong> {{ object.tenant_name }}</p>
         <p style = "margin: 0"><strong>Tenant Phone:</strong> {{ object.tenant_phone }}</p>
         <p style = "margin: 0"><strong>Street Address:</strong> {{ object.street_address }}</p>
         <p style = "margin: 0"><strong>City:</strong> {{ object.city }}</p>
         <p style = "margin: 0"><strong>State:</strong> {{ object.state }}</p>
         <p style = "margin: 0"><strong>Zip:</strong> {{ object.zip_code }}</p>
         <p style = "margin: 0"><strong>Bathrooms:</strong> {{ object.bathrooms }}</p>
         <p style = "margin: 0"><strong>Monthly Rent:</strong> {{ object.monthly_rent }}</p>
         <p style = "margin: 0"><strong>Notes:</strong> {{ object.notes }}</p>
        </td> </tr></tbody>

      </table><p></p>
         <button onclick="window.history.back()" style="background:none;border:none;cursor:pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
            Back
          </button>
      </div>
{% endblock content %}

templates/penwellrentals.html
{% extends "base.html" %} 
{% block title %}Penwell Properties{% endblock title %} 
{% block content %} 
      <div class="container">
         <h1>Apartments</h1>
         <table>
            <thead>
               <tr>
                  <th>Apt Number</th>
                  <th>Tenant Name</th>
                  <th>Tenant Phone</th>
               </tr>
            </thead>
            <tbody>
               {% for property in object_list %} 
                 {% if property.property_type == "penwell" %}
                     <tr>
                        <td><a href="{% url 'penwell_detail' property.pk %}" >{{ property.apt_numb }}</a></td>
                        <td>{{ property.tenant_name }}</td>
                        <td>{{ property.tenant_phone }}</td>
                     </tr>
                  {% endif %} 
               {% endfor %}
            </tbody>
         </table>
      </div>
      <div class="container">
         <h1>Airbnb Properties</h1>
         <table>
            <thead>
               <tr>
                  <th>Apt Number</th>
                  
               </tr>
            </thead>
            <tbody>
               {% for property in object_list %}{% if property.property_type == "airbnb" %}
               <tr>
                  <td><a href="{% url 'penwell_detail' property.pk %}" >{{ property.apt_numb }}</a></td>
               </tr>
               {% endif %}{% endfor %}
            </tbody>
         </table>
      </div>
      <div class="container">
         <h1>Commercial Properties</h1>
         <table>
            <thead>
               <tr>
                  <th>Name</th>
               </tr>
            </thead>
            <tbody>
               {% for property in object_list %}{% if property.property_type == "commercial" %}
               <tr>
                  <td><a href="{% url 'penwell_detail' property.pk %}" >{{ property.name }}</a></td>
               </tr>
               {% endif %}{% endfor %}
            </tbody>
         </table>
         <p></p>
         <button onclick="window.history.back()" style="background:none;border:none;cursor:pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
            Back
          </button>
      </div>
      {% endblock content %}
 

templates/residentialrentals.html
{% extends "base.html" %} 
{% block title %}Residential Properties{% endblock title %} 
{% block content %} 
      
      <div class="container">
         <h1>Residential Properties</h1>
         <table>
            <thead>
               <tr>
                  <th>Street Address</th>
               </tr>
            </thead>
            <tbody>
               {% for property in object_list %} 
                 {% if property.property_type == "residential" %}
                     <tr>
                        <td><a href="{% url 'residential_detail' property.pk %}">{{ property.street_address }}</a></td>

                     </tr>
               {% endif %} {% endfor %}
            </tbody>
         </table>
         <p></p>
         <button onclick="window.history.back()" style="background:none;border:none;cursor:pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
            Back
          </button>
      </div>
      {% endblock content %}